#!/usr/bin/env node

const readline = require('readline');
const GifEncoder = require('gif-encoder');
const fs = require('fs');
const zlib = require('zlib');
const log = require('debug')('gif-encoder');

var filePath
if (process.argv.length < 3) {
    filePath = 'img.gif'
} else {
    filePath = process.argv[2]; 
}

var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
});

var gif = null;

rl.on('line', line => {
    log("New line received (length: " + line.length + "): " + line.slice(0,10) + '...');
    var pixels = new Buffer(zlib.gunzipSync(new Buffer(line, 'base64')))
    log("New pixels array received (length: " + pixels.length + ")");

    if (gif === null) {
        var width, height;
        width = height = Math.sqrt(pixels.length/4)
        gif = new GifEncoder(width, height);
        let file = fs.createWriteStream(filePath);
        gif.pipe(file);

        gif.setRepeat(0);
        gif.writeHeader();
    }

    gif.addFrame(pixels);
    console.log("Frame saved");
})

rl.on('close', () => {
    if (gif) {
      console.log("GIF written successfully.");
      gif.finish();
    }
})
