#!/usr/bin/env node

var split = require('split')
var toPull = require('stream-to-pull-stream')
var pull = require('pull-stream')
var log = require('debug')('throughput (ints/s)')

var start = new Date()
var nbExecutions = 0
var reportPeriod = 3000 // ms
var done = false
function reportThroughput () {
  var end = new Date()
  var period = (end - start) / 1000 // in seconds
  start = end
  var nb = nbExecutions
  nbExecutions = 0
  log(Math.floor(nb / period))
  if (!done) setTimeout(reportThroughput, reportPeriod)
}
setTimeout(reportThroughput, reportPeriod)

var maxSteps = 0

pull(
  toPull.source(process.stdin.pipe(split(undefined, null, { trailing: false }))),
  pull.drain(function (x) {
    var output = JSON.parse(x)
    if (maxSteps < output.largest) {
      console.log(output.largest)
      maxSteps = output.largest
    }

    nbExecutions += Number.parseInt(output.range)
  }, function () {
    done = true
  })
)
