#!/bin/bash
TESTDIR=$(pwd)'/results/raytracer-'$(date "+%Y-%m-%dT%H:%M:%S")
cd ../../examples/raytracer
mkdir -p $TESTDIR
echo 'starting raytracer, will silently save throughput measurements in '$TESTDIR
./generate-angles --positions-nb=5000 | DEBUG='pando-computing:monitoring' pando raytracer.js --stdin --batch-size=2 --headless 2>$TESTDIR/devices.txt | DEBUG='throughput*' ./monitor 2>$TESTDIR/output.txt >/dev/null
