#!/bin/bash
TESTDIR=$(pwd)'/results/rlnetwork/'$(date "+%Y-%m-%dT%H:%M:%S")
cd ../../examples/rlnetwork
mkdir -p $TESTDIR
echo 'starting rlnetwork, will silently save throughput measurements in '$TESTDIR
./hyperparams --low=0.0001 --high=0.003 --steps=1000 --training-ms=55000 | DEBUG='pando-computing:monitoring' pando rldemo.js --stdin --headless --reporting-interval=60 2>$TESTDIR/devices.txt | DEBUG='throughput*' ./monitor 2>$TESTDIR/output.txt
